baseurl = "https://ykq.netlify.app"
googleAnalytics = ""
languageCode = "zh-hans"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "杨凯强 | 博客"
[menu.main]
hasChildren = true
name = "主页"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "山东"
author = "ykq"
author_image = "/images/img_0002.JPG"
bio = "我是一个自由互动艺术总监，在法国工作。专注于品牌和身份，数字和印刷。"
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [2016519.com](http://www.2016519.com)"
description = "这是个描述"
email = "y2016519@gmail.com"
home = "Home"
layout = "1"
logo = "/images/logo.png"
mobile = "137&&&&&&&&"
preloader = true
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
url = "#"
[[params.social]]
icon = "ti-twitter-alt"
url = "#"
[[params.social]]
icon = "ti-linkedin"
url = "#"
[[params.social]]
icon = "ti-github"
url = "#"
